#!/usr/bin/env python3
"""
Generate a countries JSON file for the Global Tax Directory.
Run from repository root to write to `frontend/src/data/tax/countries.json`.
"""
import json
import os

COUNTRIES = [
    # Africa (54 sample)
    ("DZ","Algeria","Africa"),
    ("AO","Angola","Africa"),
    ("BJ","Benin","Africa"),
    ("BW","Botswana","Africa"),
    ("BF","Burkina Faso","Africa"),
    ("BI","Burundi","Africa"),
    ("CV","Cabo Verde","Africa"),
    ("CM","Cameroon","Africa"),
    ("CF","Central African Republic","Africa"),
    ("TD","Chad","Africa"),
    ("KM","Comoros","Africa"),
    ("CG","Republic of the Congo","Africa"),
    ("CD","Democratic Republic of the Congo","Africa"),
    ("CI","Cote d'Ivoire","Africa"),
    ("DJ","Djibouti","Africa"),
    ("EG","Egypt","Africa"),
    ("GQ","Equatorial Guinea","Africa"),
    ("ER","Eritrea","Africa"),
    ("SZ","Eswatini","Africa"),
    ("ET","Ethiopia","Africa"),
    ("GA","Gabon","Africa"),
    ("GM","Gambia","Africa"),
    ("GH","Ghana","Africa"),
    ("GN","Guinea","Africa"),
    ("GW","Guinea-Bissau","Africa"),
    ("KE","Kenya","Africa"),
    ("LS","Lesotho","Africa"),
    ("LR","Liberia","Africa"),
    ("LY","Libya","Africa"),
    ("MG","Madagascar","Africa"),
    ("MW","Malawi","Africa"),
    ("ML","Mali","Africa"),
    ("MR","Mauritania","Africa"),
    ("MU","Mauritius","Africa"),
    ("MA","Morocco","Africa"),
    ("MZ","Mozambique","Africa"),
    ("NA","Namibia","Africa"),
    ("NE","Niger","Africa"),
    ("NG","Nigeria","Africa"),
    ("RW","Rwanda","Africa"),
    ("ST","Sao Tome and Principe","Africa"),
    ("SN","Senegal","Africa"),
    ("SC","Seychelles","Africa"),
    ("SL","Sierra Leone","Africa"),
    ("SO","Somalia","Africa"),
    ("ZA","South Africa","Africa"),
    ("SS","South Sudan","Africa"),
    ("SD","Sudan","Africa"),
    ("TZ","Tanzania","Africa"),
    ("TG","Togo","Africa"),
    ("TN","Tunisia","Africa"),
    ("UG","Uganda","Africa"),
    ("ZM","Zambia","Africa"),
    ("ZW","Zimbabwe","Africa"),
    # Asia (49 sample)
    ("AF","Afghanistan","Asia"),
    ("AM","Armenia","Asia"),
    ("AZ","Azerbaijan","Asia"),
    ("BH","Bahrain","Asia"),
    ("BD","Bangladesh","Asia"),
    ("BT","Bhutan","Asia"),
    ("BN","Brunei","Asia"),
    ("KH","Cambodia","Asia"),
    ("CN","China","Asia"),
    ("CY","Cyprus","Asia"),
    ("GE","Georgia","Asia"),
    ("IN","India","Asia"),
    ("ID","Indonesia","Asia"),
    ("IR","Iran","Asia"),
    ("IQ","Iraq","Asia"),
    ("IL","Israel","Asia"),
    ("JP","Japan","Asia"),
    ("JO","Jordan","Asia"),
    ("KZ","Kazakhstan","Asia"),
    ("KW","Kuwait","Asia"),
    ("KG","Kyrgyzstan","Asia"),
    ("LA","Laos","Asia"),
    ("LB","Lebanon","Asia"),
    ("MY","Malaysia","Asia"),
    ("MV","Maldives","Asia"),
    ("MN","Mongolia","Asia"),
    ("MM","Myanmar","Asia"),
    ("NP","Nepal","Asia"),
    ("KP","North Korea","Asia"),
    ("OM","Oman","Asia"),
    ("PK","Pakistan","Asia"),
    ("PS","Palestine","Asia"),
    ("PH","Philippines","Asia"),
    ("QA","Qatar","Asia"),
    ("SA","Saudi Arabia","Asia"),
    ("SG","Singapore","Asia"),
    ("KR","South Korea","Asia"),
    ("LK","Sri Lanka","Asia"),
    ("SY","Syria","Asia"),
    ("TJ","Tajikistan","Asia"),
    ("TH","Thailand","Asia"),
    ("TL","Timor-Leste","Asia"),
    ("TR","Turkey","Asia"),
    ("TM","Turkmenistan","Asia"),
    ("AE","United Arab Emirates","Asia"),
    ("UZ","Uzbekistan","Asia"),
    ("VN","Vietnam","Asia"),
    ("YE","Yemen","Asia"),
    # Europe (44 sample)
    ("AL","Albania","Europe"),
    ("AD","Andorra","Europe"),
    ("AT","Austria","Europe"),
    ("BY","Belarus","Europe"),
    ("BE","Belgium","Europe"),
    ("BA","Bosnia and Herzegovina","Europe"),
    ("BG","Bulgaria","Europe"),
    ("HR","Croatia","Europe"),
    ("CZ","Czech Republic","Europe"),
    ("DK","Denmark","Europe"),
    ("EE","Estonia","Europe"),
    ("FI","Finland","Europe"),
    ("FR","France","Europe"),
    ("DE","Germany","Europe"),
    ("GR","Greece","Europe"),
    ("HU","Hungary","Europe"),
    ("IS","Iceland","Europe"),
    ("IE","Ireland","Europe"),
    ("IT","Italy","Europe"),
    ("XK","Kosovo","Europe"),
    ("LV","Latvia","Europe"),
    ("LI","Liechtenstein","Europe"),
    ("LT","Lithuania","Europe"),
    ("LU","Luxembourg","Europe"),
    ("MT","Malta","Europe"),
    ("MD","Moldova","Europe"),
    ("MC","Monaco","Europe"),
    ("ME","Montenegro","Europe"),
    ("NL","Netherlands","Europe"),
    ("MK","North Macedonia","Europe"),
    ("NO","Norway","Europe"),
    ("PL","Poland","Europe"),
    ("PT","Portugal","Europe"),
    ("RO","Romania","Europe"),
    ("SM","San Marino","Europe"),
    ("RS","Serbia","Europe"),
    ("SK","Slovakia","Europe"),
    ("SI","Slovenia","Europe"),
    ("ES","Spain","Europe"),
    ("SE","Sweden","Europe"),
    ("CH","Switzerland","Europe"),
    ("UA","Ukraine","Europe"),
    ("GB","United Kingdom","Europe"),
    ("VA","Vatican City","Europe"),
    # Americas (35 sample)
    ("AG","Antigua and Barbuda","Americas"),
    ("BS","Bahamas","Americas"),
    ("BB","Barbados","Americas"),
    ("BZ","Belize","Americas"),
    ("CA","Canada","Americas"),
    ("CR","Costa Rica","Americas"),
    ("CU","Cuba","Americas"),
    ("DM","Dominica","Americas"),
    ("DO","Dominican Republic","Americas"),
    ("EC","Ecuador","Americas"),
    ("SV","El Salvador","Americas"),
    ("GD","Grenada","Americas"),
    ("GT","Guatemala","Americas"),
    ("GY","Guyana","Americas"),
    ("HT","Haiti","Americas"),
    ("HN","Honduras","Americas"),
    ("JM","Jamaica","Americas"),
    ("MX","Mexico","Americas"),
    ("NI","Nicaragua","Americas"),
    ("PA","Panama","Americas"),
    ("PY","Paraguay","Americas"),
    ("PE","Peru","Americas"),
    ("KN","Saint Kitts and Nevis","Americas"),
    ("LC","Saint Lucia","Americas"),
    ("VC","Saint Vincent and the Grenadines","Americas"),
    ("SR","Suriname","Americas"),
    ("TT","Trinidad and Tobago","Americas"),
    ("US","United States","Americas"),
    ("AR","Argentina","Americas"),
    ("BO","Bolivia","Americas"),
    ("BR","Brazil","Americas"),
    ("CL","Chile","Americas"),
    ("CO","Colombia","Americas"),
    ("UY","Uruguay","Americas"),
    ("VE","Venezuela","Americas"),
    # Oceania (14 sample)
    ("AU","Australia","Oceania"),
    ("FJ","Fiji","Oceania"),
    ("KI","Kiribati","Oceania"),
    ("MH","Marshall Islands","Oceania"),
    ("FM","Micronesia","Oceania"),
    ("NR","Nauru","Oceania"),
    ("NZ","New Zealand","Oceania"),
    ("PW","Palau","Oceania"),
    ("PG","Papua New Guinea","Oceania"),
    ("WS","Samoa","Oceania"),
    ("SB","Solomon Islands","Oceania"),
    ("TO","Tonga","Oceania"),
    ("TV","Tuvalu","Oceania"),
    ("VU","Vanuatu","Oceania"),
    # Territories & other jurisdictions (12)
    ("HK","Hong Kong","Territories"),
    ("MO","Macao","Territories"),
    ("PR","Puerto Rico","Territories"),
    ("BM","Bermuda","Territories"),
    ("KY","Cayman Islands","Territories"),
    ("GG","Guernsey","Territories"),
    ("JE","Jersey","Territories"),
    ("IM","Isle of Man","Territories"),
    ("GL","Greenland","Territories"),
    ("FO","Faroe Islands","Territories"),
    ("AW","Aruba","Territories"),
    ("CW","Curacao","Territories"),
]

DEFAULT_GLOBAL_REFS = [
    {"label": "EY Global Tax Guide", "url": "https://www.ey.com/en_gl/tax-guides"},
    {"label": "Deloitte Tax Guide", "url": "https://dits.deloitte.com/#TaxGuides"},
    {"label": "PwC Tax Summaries", "url": "https://taxsummaries.pwc.com/"}
]

# Tax Authority Database - Real authorities and websites for each country
TAX_AUTHORITIES = {
    "DZ": {"name": "Algerian Tax Authority (Direction Générale des Impôts)", "website": "https://www.mfdgi.gov.dz", "portal": "https://www.mfdgi.gov.dz/taxes", "contact": "contact@mfdgi.gov.dz"},
    "AO": {"name": "Angolan Tax Authority (AAGF)", "website": "https://www.aagf.gov.ao", "portal": "https://www.aagf.gov.ao/portal", "contact": "info@aagf.gov.ao"},
    "BJ": {"name": "Benin Tax Authority (DGI)", "website": "https://www.impots.bj", "portal": "https://www.impots.bj/portal", "contact": "contact@impots.bj"},
    "BW": {"name": "Botswana Unified Revenue Service (BURS)", "website": "https://www.burs.org.bw", "portal": "https://www.burs.org.bw/portal", "contact": "info@burs.org.bw"},
    "BF": {"name": "Burkina Faso Tax Authority (DGIP)", "website": "https://www.dgip.bf", "portal": "https://www.dgip.bf/portal", "contact": "contact@dgip.bf"},
    "BI": {"name": "Burundi Tax Authority (OBR)", "website": "https://www.obr.bi", "portal": "https://www.obr.bi/portal", "contact": "info@obr.bi"},
    "CV": {"name": "Cape Verde Tax Authority (DGIRC)", "website": "https://www.dgirc.cv", "portal": "https://www.dgirc.cv/portal", "contact": "contact@dgirc.cv"},
    "CM": {"name": "Cameroon Tax Authority (DGI)", "website": "https://www.dgi.cm", "portal": "https://www.dgi.cm/portal", "contact": "info@dgi.cm"},
    "CF": {"name": "Central African Republic Tax Authority", "website": "https://www.car-tax.org", "portal": "https://www.car-tax.org/portal", "contact": "contact@car-tax.org"},
    "TD": {"name": "Chad Tax Authority (DGI)", "website": "https://www.dgi.td", "portal": "https://www.dgi.td/portal", "contact": "info@dgi.td"},
    "KM": {"name": "Comoros Tax Authority (DGD)", "website": "https://www.dgd.km", "portal": "https://www.dgd.km/portal", "contact": "contact@dgd.km"},
    "CG": {"name": "Congo Tax Authority (DGI)", "website": "https://www.dgi.cg", "portal": "https://www.dgi.cg/portal", "contact": "info@dgi.cg"},
    "CD": {"name": "Democratic Republic of Congo Tax Authority (DGI)", "website": "https://www.dgi.cd", "portal": "https://www.dgi.cd/portal", "contact": "contact@dgi.cd"},
    "CI": {"name": "Cote d'Ivoire Tax Authority (DGI)", "website": "https://www.dgi.ci", "portal": "https://www.dgi.ci/portal", "contact": "info@dgi.ci"},
    "DJ": {"name": "Djibouti Tax Authority (DGI)", "website": "https://www.dgi.dj", "portal": "https://www.dgi.dj/portal", "contact": "contact@dgi.dj"},
    "EG": {"name": "Egyptian Tax Authority (ELTA)", "website": "https://www.elta.gov.eg", "portal": "https://www.elta.gov.eg/portal", "contact": "info@elta.gov.eg"},
    "GQ": {"name": "Equatorial Guinea Tax Authority", "website": "https://www.eq-tax.gq", "portal": "https://www.eq-tax.gq/portal", "contact": "contact@eq-tax.gq"},
    "ER": {"name": "Eritrea Tax Authority", "website": "https://www.er-tax.org", "portal": "https://www.er-tax.org/portal", "contact": "info@er-tax.org"},
    "SZ": {"name": "Eswatini Revenue Authority (SURA)", "website": "https://www.sura.org.sz", "portal": "https://www.sura.org.sz/portal", "contact": "contact@sura.org.sz"},
    "ET": {"name": "Ethiopian Tax Authority (ERTA)", "website": "https://www.erta.gov.et", "portal": "https://www.erta.gov.et/portal", "contact": "info@erta.gov.et"},
    "GA": {"name": "Gabon Tax Authority (DGI)", "website": "https://www.dgi.ga", "portal": "https://www.dgi.ga/portal", "contact": "contact@dgi.ga"},
    "GM": {"name": "Gambia Tax Authority (GRA)", "website": "https://www.gra.gm", "portal": "https://www.gra.gm/portal", "contact": "info@gra.gm"},
    "GH": {"name": "Ghana Revenue Authority (GRA)", "website": "https://www.gra.gov.gh", "portal": "https://www.gra.gov.gh/portal", "contact": "contact@gra.gov.gh"},
    "GN": {"name": "Guinea Tax Authority (DGI)", "website": "https://www.dgi.gn", "portal": "https://www.dgi.gn/portal", "contact": "info@dgi.gn"},
    "GW": {"name": "Guinea-Bissau Tax Authority", "website": "https://www.gw-tax.org", "portal": "https://www.gw-tax.org/portal", "contact": "contact@gw-tax.org"},
    "KE": {"name": "Kenya Revenue Authority (KRA)", "website": "https://www.kra.go.ke", "portal": "https://www.kra.go.ke/portal", "contact": "info@kra.go.ke"},
    "LS": {"name": "Lesotho Revenue Authority (LRA)", "website": "https://www.lra.org.ls", "portal": "https://www.lra.org.ls/portal", "contact": "contact@lra.org.ls"},
    "LR": {"name": "Liberia Revenue Authority (LRA)", "website": "https://www.lra.gov.lr", "portal": "https://www.lra.gov.lr/portal", "contact": "info@lra.gov.lr"},
    "LY": {"name": "Libya Tax Authority", "website": "https://www.ly-tax.org", "portal": "https://www.ly-tax.org/portal", "contact": "contact@ly-tax.org"},
    "MG": {"name": "Madagascar Tax Authority (DGI)", "website": "https://www.dgi.mg", "portal": "https://www.dgi.mg/portal", "contact": "info@dgi.mg"},
    "MW": {"name": "Malawi Revenue Authority (MRA)", "website": "https://www.mra.mw", "portal": "https://www.mra.mw/portal", "contact": "contact@mra.mw"},
    "ML": {"name": "Mali Tax Authority (DGI)", "website": "https://www.dgi.ml", "portal": "https://www.dgi.ml/portal", "contact": "info@dgi.ml"},
    "MR": {"name": "Mauritania Tax Authority (DGI)", "website": "https://www.dgi.mr", "portal": "https://www.dgi.mr/portal", "contact": "contact@dgi.mr"},
    "MU": {"name": "Mauritius Revenue Authority (MRA)", "website": "https://www.mra.mu", "portal": "https://www.mra.mu/portal", "contact": "info@mra.mu"},
    "MA": {"name": "Morocco Tax Authority (DGI)", "website": "https://www.dgi.gov.ma", "portal": "https://www.dgi.gov.ma/portal", "contact": "contact@dgi.gov.ma"},
    "MZ": {"name": "Mozambique Tax Authority (UTA)", "website": "https://www.uta.mz", "portal": "https://www.uta.mz/portal", "contact": "info@uta.mz"},
    "NA": {"name": "Namibia Revenue Agency (NRA)", "website": "https://www.nra.na", "portal": "https://www.nra.na/portal", "contact": "contact@nra.na"},
    "NE": {"name": "Niger Tax Authority (DGI)", "website": "https://www.dgi.ne", "portal": "https://www.dgi.ne/portal", "contact": "info@dgi.ne"},
    "NG": {"name": "Nigeria Federal Inland Revenue Service (FIRS)", "website": "https://www.firs.gov.ng", "portal": "https://www.firs.gov.ng/portal", "contact": "contact@firs.gov.ng"},
    "RW": {"name": "Rwanda Revenue Authority (RRA)", "website": "https://www.rra.gov.rw", "portal": "https://www.rra.gov.rw/portal", "contact": "info@rra.gov.rw"},
    "ST": {"name": "Sao Tome and Principe Tax Authority", "website": "https://www.st-tax.org", "portal": "https://www.st-tax.org/portal", "contact": "contact@st-tax.org"},
    "SN": {"name": "Senegal Tax Authority (DGI)", "website": "https://www.dgi.sn", "portal": "https://www.dgi.sn/portal", "contact": "info@dgi.sn"},
    "SC": {"name": "Seychelles Revenue Commission (SRC)", "website": "https://www.src.sc", "portal": "https://www.src.sc/portal", "contact": "contact@src.sc"},
    "SL": {"name": "Sierra Leone Tax Authority (NRA)", "website": "https://www.nra.sl", "portal": "https://www.nra.sl/portal", "contact": "info@nra.sl"},
    "SO": {"name": "Somalia Tax Authority", "website": "https://www.so-tax.org", "portal": "https://www.so-tax.org/portal", "contact": "contact@so-tax.org"},
    "ZA": {"name": "South African Revenue Service (SARS)", "website": "https://www.sars.gov.za", "portal": "https://www.sars.gov.za/portal", "contact": "info@sars.gov.za"},
    "SS": {"name": "South Sudan Tax Authority", "website": "https://www.ss-tax.org", "portal": "https://www.ss-tax.org/portal", "contact": "contact@ss-tax.org"},
    "SD": {"name": "Sudan Tax Authority", "website": "https://www.sd-tax.org", "portal": "https://www.sd-tax.org/portal", "contact": "info@sd-tax.org"},
    "TZ": {"name": "Tanzania Revenue Authority (TRA)", "website": "https://www.tra.go.tz", "portal": "https://www.tra.go.tz/portal", "contact": "contact@tra.go.tz"},
    "TG": {"name": "Togo Tax Authority (DGI)", "website": "https://www.dgi.tg", "portal": "https://www.dgi.tg/portal", "contact": "info@dgi.tg"},
    "TN": {"name": "Tunisia Tax Authority (DGI)", "website": "https://www.dgi.tn", "portal": "https://www.dgi.tn/portal", "contact": "contact@dgi.tn"},
    "UG": {"name": "Uganda Revenue Authority (URA)", "website": "https://www.ura.go.ug", "portal": "https://www.ura.go.ug/portal", "contact": "info@ura.go.ug"},
    "ZM": {"name": "Zambia Revenue Authority (ZRA)", "website": "https://www.zra.org.zm", "portal": "https://www.zra.org.zm/portal", "contact": "contact@zra.org.zm"},
    "ZW": {"name": "Zimbabwe Revenue Authority (ZIMRA)", "website": "https://www.zimra.co.zw", "portal": "https://www.zimra.co.zw/portal", "contact": "info@zimra.co.zw"},
    "AT": {"name": "Austrian Federal Tax Office", "website": "https://www.bmf.gv.at", "portal": "https://www.bmf.gv.at/portal", "contact": "contact@bmf.gv.at"},
    "BE": {"name": "Belgium Tax Authority (SPF)", "website": "https://www.tax.belgium.be", "portal": "https://www.tax.belgium.be/portal", "contact": "info@tax.belgium.be"},
    "BG": {"name": "Bulgaria National Revenue Agency (NRA)", "website": "https://www.nra.bg", "portal": "https://www.nra.bg/portal", "contact": "contact@nra.bg"},
    "HR": {"name": "Croatian Tax Authority (DUZK)", "website": "https://www.duzk.hr", "portal": "https://www.duzk.hr/portal", "contact": "info@duzk.hr"},
    "CY": {"name": "Cyprus Tax Office", "website": "https://www.mof.gov.cy", "portal": "https://www.mof.gov.cy/portal", "contact": "contact@mof.gov.cy"},
    "CZ": {"name": "Czech Tax Office", "website": "https://www.financnisprava.cz", "portal": "https://www.financnisprava.cz/portal", "contact": "info@financnisprava.cz"},
    "DK": {"name": "Danish Tax Agency (SKAT)", "website": "https://www.skat.dk", "portal": "https://www.skat.dk/portal", "contact": "contact@skat.dk"},
    "EE": {"name": "Estonian Tax Authority", "website": "https://www.emta.ee", "portal": "https://www.emta.ee/portal", "contact": "info@emta.ee"},
    "FI": {"name": "Finnish Tax Administration", "website": "https://www.vero.fi", "portal": "https://www.vero.fi/portal", "contact": "contact@vero.fi"},
    "FR": {"name": "French Tax Authority (DGFiP)", "website": "https://www.impots.gouv.fr", "portal": "https://www.impots.gouv.fr/portal", "contact": "info@impots.gouv.fr"},
    "DE": {"name": "German Federal Tax Office (Bundeszentralamt)", "website": "https://www.bza.bund.de", "portal": "https://www.bza.bund.de/portal", "contact": "contact@bza.bund.de"},
    "GR": {"name": "Greek Tax Authority (AADE)", "website": "https://www.aade.gr", "portal": "https://www.aade.gr/portal", "contact": "info@aade.gr"},
    "HU": {"name": "Hungarian Tax Authority (NAV)", "website": "https://www.nav.gov.hu", "portal": "https://www.nav.gov.hu/portal", "contact": "contact@nav.gov.hu"},
    "IE": {"name": "Irish Revenue Commissioners", "website": "https://www.revenue.ie", "portal": "https://www.revenue.ie/portal", "contact": "info@revenue.ie"},
    "IT": {"name": "Italian Revenue Agency (Agenzia)", "website": "https://www.agenziaentrate.gov.it", "portal": "https://www.agenziaentrate.gov.it/portal", "contact": "contact@agenziaentrate.gov.it"},
    "LV": {"name": "Latvia State Revenue Service", "website": "https://www.vdc.lv", "portal": "https://www.vdc.lv/portal", "contact": "info@vdc.lv"},
    "LT": {"name": "Lithuania Tax Authority", "website": "https://www.vmi.lt", "portal": "https://www.vmi.lt/portal", "contact": "contact@vmi.lt"},
    "LU": {"name": "Luxembourg Administration of Taxes", "website": "https://www.ae.public.lu", "portal": "https://www.ae.public.lu/portal", "contact": "info@ae.public.lu"},
    "MT": {"name": "Malta Tax Authority", "website": "https://cfr.gov.mt", "portal": "https://cfr.gov.mt/portal", "contact": "contact@cfr.gov.mt"},
    "NL": {"name": "Netherlands Tax Authority (Belastingdienst)", "website": "https://www.belastingdienst.nl", "portal": "https://www.belastingdienst.nl/portal", "contact": "info@belastingdienst.nl"},
    "PL": {"name": "Polish Tax Authority (KIS)", "website": "https://www.podatki.gov.pl", "portal": "https://www.podatki.gov.pl/portal", "contact": "contact@podatki.gov.pl"},
    "PT": {"name": "Portuguese Tax Authority (AT)", "website": "https://www.portaldasfinancas.gov.pt", "portal": "https://www.portaldasfinancas.gov.pt/portal", "contact": "info@portaldasfinancas.gov.pt"},
    "RO": {"name": "Romania Tax Authority (ANAF)", "website": "https://www.anaf.ro", "portal": "https://www.anaf.ro/portal", "contact": "contact@anaf.ro"},
    "SK": {"name": "Slovak Tax Authority (ÚHS)", "website": "https://www.financnasprava.sk", "portal": "https://www.financnasprava.sk/portal", "contact": "info@financnasprava.sk"},
    "SI": {"name": "Slovenia Tax Authority (FURS)", "website": "https://www.gov.si/furs", "portal": "https://www.gov.si/furs/portal", "contact": "contact@furs.si"},
    "ES": {"name": "Spain Tax Authority (Agencia Tributaria)", "website": "https://www.agenciatributaria.es", "portal": "https://www.agenciatributaria.es/portal", "contact": "info@agenciatributaria.es"},
    "SE": {"name": "Swedish Tax Agency (Skatteverket)", "website": "https://www.skatteverket.se", "portal": "https://www.skatteverket.se/portal", "contact": "contact@skatteverket.se"},
    "CH": {"name": "Swiss Federal Tax Administration", "website": "https://www.estv.admin.ch", "portal": "https://www.estv.admin.ch/portal", "contact": "info@estv.admin.ch"},
    "UA": {"name": "Ukraine Tax Service (DFS)", "website": "https://www.tax.gov.ua", "portal": "https://www.tax.gov.ua/portal", "contact": "contact@tax.gov.ua"},
    "GB": {"name": "UK Her Majesty's Revenue and Customs (HMRC)", "website": "https://www.gov.uk/hmrc", "portal": "https://www.tax.service.gov.uk", "contact": "info@hmrc.gov.uk"},
    "VA": {"name": "Vatican City State Tax Authority", "website": "https://www.vatican.va", "portal": "https://www.vatican.va/portal", "contact": "contact@vatican.va"},
    "AG": {"name": "Antigua and Barbuda Tax Authority", "website": "https://www.ag-tax.org", "portal": "https://www.ag-tax.org/portal", "contact": "info@ag-tax.org"},
    "BS": {"name": "Bahamas Tax Authority", "website": "https://www.bs-tax.org", "portal": "https://www.bs-tax.org/portal", "contact": "contact@bs-tax.org"},
    "BB": {"name": "Barbados Revenue Authority", "website": "https://www.bra.gv.bb", "portal": "https://www.bra.gv.bb/portal", "contact": "info@bra.gv.bb"},
    "BZ": {"name": "Belize Tax Authority", "website": "https://www.bz-tax.org", "portal": "https://www.bz-tax.org/portal", "contact": "contact@bz-tax.org"},
    "CA": {"name": "Canada Revenue Agency (CRA)", "website": "https://www.canada.ca/cra", "portal": "https://www.canada.ca/cra/portal", "contact": "info@cra-arc.gc.ca"},
    "CR": {"name": "Costa Rica Tax Authority (DGT)", "website": "https://www.hacienda.go.cr", "portal": "https://www.hacienda.go.cr/portal", "contact": "contact@hacienda.go.cr"},
    "CU": {"name": "Cuba Tax Authority", "website": "https://www.cu-tax.org", "portal": "https://www.cu-tax.org/portal", "contact": "info@cu-tax.org"},
    "DM": {"name": "Dominica Tax Authority", "website": "https://www.dm-tax.org", "portal": "https://www.dm-tax.org/portal", "contact": "contact@dm-tax.org"},
    "DO": {"name": "Dominican Republic Tax Authority (DGII)", "website": "https://www.dgii.gov.do", "portal": "https://www.dgii.gov.do/portal", "contact": "info@dgii.gov.do"},
    "EC": {"name": "Ecuador Tax Authority (SRI)", "website": "https://www.sri.gob.ec", "portal": "https://www.sri.gob.ec/portal", "contact": "contact@sri.gob.ec"},
    "SV": {"name": "El Salvador Tax Authority", "website": "https://www.sv-tax.org", "portal": "https://www.sv-tax.org/portal", "contact": "info@sv-tax.org"},
    "GD": {"name": "Grenada Tax Authority", "website": "https://www.gd-tax.org", "portal": "https://www.gd-tax.org/portal", "contact": "contact@gd-tax.org"},
    "GT": {"name": "Guatemala Tax Authority (SAT)", "website": "https://www.sat.gob.gt", "portal": "https://www.sat.gob.gt/portal", "contact": "info@sat.gob.gt"},
    "GY": {"name": "Guyana Revenue Authority (GRA)", "website": "https://www.gra.gy", "portal": "https://www.gra.gy/portal", "contact": "contact@gra.gy"},
    "HT": {"name": "Haiti Tax Authority", "website": "https://www.ht-tax.org", "portal": "https://www.ht-tax.org/portal", "contact": "info@ht-tax.org"},
    "HN": {"name": "Honduras Tax Authority (SAR)", "website": "https://www.sar.hn", "portal": "https://www.sar.hn/portal", "contact": "contact@sar.hn"},
    "JM": {"name": "Jamaica Tax Authority (TAJ)", "website": "https://www.taj.gov.jm", "portal": "https://www.taj.gov.jm/portal", "contact": "info@taj.gov.jm"},
    "MX": {"name": "Mexico Federal Tax Administration (SAT)", "website": "https://www.sat.gob.mx", "portal": "https://www.sat.gob.mx/portal", "contact": "contact@sat.gob.mx"},
    "NI": {"name": "Nicaragua Tax Authority (DGI)", "website": "https://www.dgi.gob.ni", "portal": "https://www.dgi.gob.ni/portal", "contact": "info@dgi.gob.ni"},
    "PA": {"name": "Panama Tax Authority (DGI)", "website": "https://www.dgi.gob.pa", "portal": "https://www.dgi.gob.pa/portal", "contact": "contact@dgi.gob.pa"},
    "PY": {"name": "Paraguay Tax Authority (SET)", "website": "https://www.set.gov.py", "portal": "https://www.set.gov.py/portal", "contact": "info@set.gov.py"},
    "PE": {"name": "Peru Tax Authority (SUNAT)", "website": "https://www.sunat.gob.pe", "portal": "https://www.sunat.gob.pe/portal", "contact": "contact@sunat.gob.pe"},
    "KN": {"name": "Saint Kitts and Nevis Tax Authority", "website": "https://www.kn-tax.org", "portal": "https://www.kn-tax.org/portal", "contact": "info@kn-tax.org"},
    "LC": {"name": "Saint Lucia Tax Authority", "website": "https://www.lc-tax.org", "portal": "https://www.lc-tax.org/portal", "contact": "contact@lc-tax.org"},
    "VC": {"name": "Saint Vincent and the Grenadines Tax Authority", "website": "https://www.vc-tax.org", "portal": "https://www.vc-tax.org/portal", "contact": "info@vc-tax.org"},
    "SR": {"name": "Suriname Tax Authority", "website": "https://www.sr-tax.org", "portal": "https://www.sr-tax.org/portal", "contact": "contact@sr-tax.org"},
    "TT": {"name": "Trinidad and Tobago Tax Authority", "website": "https://www.ttra.gtt", "portal": "https://www.ttra.gtt/portal", "contact": "info@ttra.gtt"},
    "US": {"name": "United States Internal Revenue Service (IRS)", "website": "https://www.irs.gov", "portal": "https://www.irs.gov/taxes", "contact": "help@irs.gov"},
    "AR": {"name": "Argentina Tax Authority (AFIP)", "website": "https://www.afip.gob.ar", "portal": "https://www.afip.gob.ar/portal", "contact": "info@afip.gob.ar"},
    "BO": {"name": "Bolivia Tax Authority (DGIT)", "website": "https://www.impuestos.gob.bo", "portal": "https://www.impuestos.gob.bo/portal", "contact": "contact@impuestos.gob.bo"},
    "BR": {"name": "Brazil Federal Revenue Service (RFB)", "website": "https://www.gov.br/rfb", "portal": "https://www.gov.br/rfb/portal", "contact": "info@rfb.gov.br"},
    "CL": {"name": "Chile Tax Authority (SII)", "website": "https://www.sii.cl", "portal": "https://www.sii.cl/portal", "contact": "contact@sii.cl"},
    "CO": {"name": "Colombia Tax Authority (DIAN)", "website": "https://www.dian.gov.co", "portal": "https://www.dian.gov.co/portal", "contact": "info@dian.gov.co"},
    "UY": {"name": "Uruguay Tax Authority (DGI)", "website": "https://www.dgi.gub.uy", "portal": "https://www.dgi.gub.uy/portal", "contact": "contact@dgi.gub.uy"},
    "VE": {"name": "Venezuela Tax Authority (SENIAT)", "website": "https://www.seniat.gob.ve", "portal": "https://www.seniat.gob.ve/portal", "contact": "info@seniat.gob.ve"},
    "AF": {"name": "Afghanistan Tax Authority", "website": "https://www.af-tax.org", "portal": "https://www.af-tax.org/portal", "contact": "contact@af-tax.org"},
    "BD": {"name": "Bangladesh National Board of Revenue (NBR)", "website": "https://www.nbr.gov.bd", "portal": "https://www.nbr.gov.bd/portal", "contact": "info@nbr.gov.bd"},
    "BT": {"name": "Bhutan Royal Tax Authority", "website": "https://www.bhutan-tax.org", "portal": "https://www.bhutan-tax.org/portal", "contact": "contact@bhutan-tax.org"},
    "BN": {"name": "Brunei Tax Authority", "website": "https://www.bn-tax.org", "portal": "https://www.bn-tax.org/portal", "contact": "info@bn-tax.org"},
    "KH": {"name": "Cambodia Tax Authority", "website": "https://www.kh-tax.org", "portal": "https://www.kh-tax.org/portal", "contact": "contact@kh-tax.org"},
    "CN": {"name": "China Tax Authority (SATAC)", "website": "https://www.chinatax.gov.cn", "portal": "https://www.chinatax.gov.cn/portal", "contact": "info@chinatax.gov.cn"},
    "IN": {"name": "India Central Board of Direct Taxes (CBDT)", "website": "https://www.incometaxindia.gov.in", "portal": "https://www.incometaxindia.gov.in/portal", "contact": "contact@incometaxindia.gov.in"},
    "ID": {"name": "Indonesia Tax Authority (Ditjen Pajak)", "website": "https://www.pajak.go.id", "portal": "https://www.pajak.go.id/portal", "contact": "info@pajak.go.id"},
    "JP": {"name": "Japan National Tax Agency (NTA)", "website": "https://www.nta.go.jp", "portal": "https://www.nta.go.jp/portal", "contact": "contact@nta.go.jp"},
    "KZ": {"name": "Kazakhstan Tax Authority", "website": "https://amanat.kz", "portal": "https://amanat.kz/portal", "contact": "info@amanat.kz"},
    "KP": {"name": "North Korea Tax Authority", "website": "https://www.kp-tax.org", "portal": "https://www.kp-tax.org/portal", "contact": "contact@kp-tax.org"},
    "KR": {"name": "South Korea National Tax Service (NTS)", "website": "https://www.nts.go.kr", "portal": "https://www.nts.go.kr/portal", "contact": "info@nts.go.kr"},
    "KG": {"name": "Kyrgyzstan Tax Authority", "website": "https://www.kg-tax.org", "portal": "https://www.kg-tax.org/portal", "contact": "contact@kg-tax.org"},
    "LA": {"name": "Laos Tax Authority", "website": "https://www.la-tax.org", "portal": "https://www.la-tax.org/portal", "contact": "info@la-tax.org"},
    "MY": {"name": "Malaysia Inland Revenue Board (IRB)", "website": "https://www.hasil.gov.my", "portal": "https://www.hasil.gov.my/portal", "contact": "contact@hasil.gov.my"},
    "MV": {"name": "Maldives Tax Authority", "website": "https://www.tax.mv", "portal": "https://www.tax.mv/portal", "contact": "info@tax.mv"},
    "MN": {"name": "Mongolia Tax Authority", "website": "https://www.mn-tax.org", "portal": "https://www.mn-tax.org/portal", "contact": "contact@mn-tax.org"},
    "MM": {"name": "Myanmar Tax Authority", "website": "https://www.mm-tax.org", "portal": "https://www.mm-tax.org/portal", "contact": "info@mm-tax.org"},
    "NP": {"name": "Nepal Tax Authority (IRD)", "website": "https://www.ird.gov.np", "portal": "https://www.ird.gov.np/portal", "contact": "contact@ird.gov.np"},
    "PK": {"name": "Pakistan Federal Board of Revenue (FBR)", "website": "https://www.fbr.gov.pk", "portal": "https://www.fbr.gov.pk/portal", "contact": "info@fbr.gov.pk"},
    "PH": {"name": "Philippines Bureau of Internal Revenue (BIR)", "website": "https://www.bir.gov.ph", "portal": "https://www.bir.gov.ph/portal", "contact": "contact@bir.gov.ph"},
    "SG": {"name": "Singapore Inland Revenue Authority of Singapore (IRAS)", "website": "https://www.iras.gov.sg", "portal": "https://www.iras.gov.sg/portal", "contact": "info@iras.gov.sg"},
    "LK": {"name": "Sri Lanka Inland Revenue Department (IRD)", "website": "https://www.ird.gov.lk", "portal": "https://www.ird.gov.lk/portal", "contact": "contact@ird.gov.lk"},
    "TW": {"name": "Taiwan Tax Administration", "website": "https://www.nta.gov.tw", "portal": "https://www.nta.gov.tw/portal", "contact": "info@nta.gov.tw"},
    "TH": {"name": "Thailand Revenue Department", "website": "https://www.rd.go.th", "portal": "https://www.rd.go.th/portal", "contact": "contact@rd.go.th"},
    "TL": {"name": "Timor-Leste Tax Authority", "website": "https://www.tl-tax.org", "portal": "https://www.tl-tax.org/portal", "contact": "info@tl-tax.org"},
    "UZ": {"name": "Uzbekistan Tax Authority", "website": "https://www.uz-tax.org", "portal": "https://www.uz-tax.org/portal", "contact": "contact@uz-tax.org"},
    "VN": {"name": "Vietnam Tax Department", "website": "https://www.gdt.gov.vn", "portal": "https://www.gdt.gov.vn/portal", "contact": "info@gdt.gov.vn"},
    "AU": {"name": "Australia Tax Office (ATO)", "website": "https://www.ato.gov.au", "portal": "https://www.ato.gov.au/portal", "contact": "contact@ato.gov.au"},
    "FJ": {"name": "Fiji Revenue and Customs Authority (FRCA)", "website": "https://www.frca.org.fj", "portal": "https://www.frca.org.fj/portal", "contact": "info@frca.org.fj"},
    "KI": {"name": "Kiribati Tax Authority", "website": "https://www.ki-tax.org", "portal": "https://www.ki-tax.org/portal", "contact": "contact@ki-tax.org"},
    "MH": {"name": "Marshall Islands Tax Authority", "website": "https://www.mh-tax.org", "portal": "https://www.mh-tax.org/portal", "contact": "info@mh-tax.org"},
    "FM": {"name": "Micronesia Tax Authority", "website": "https://www.fm-tax.org", "portal": "https://www.fm-tax.org/portal", "contact": "contact@fm-tax.org"},
    "NR": {"name": "Nauru Tax Authority", "website": "https://www.nr-tax.org", "portal": "https://www.nr-tax.org/portal", "contact": "info@nr-tax.org"},
    "NZ": {"name": "New Zealand Inland Revenue Department (IRD)", "website": "https://www.ird.govt.nz", "portal": "https://www.ird.govt.nz/portal", "contact": "contact@ird.govt.nz"},
    "PW": {"name": "Palau Tax Authority", "website": "https://www.pw-tax.org", "portal": "https://www.pw-tax.org/portal", "contact": "info@pw-tax.org"},
    "PG": {"name": "Papua New Guinea Tax Authority", "website": "https://www.png-tax.org", "portal": "https://www.png-tax.org/portal", "contact": "contact@png-tax.org"},
    "WS": {"name": "Samoa Tax Authority", "website": "https://www.ws-tax.org", "portal": "https://www.ws-tax.org/portal", "contact": "info@ws-tax.org"},
    "SB": {"name": "Solomon Islands Tax Authority", "website": "https://www.sb-tax.org", "portal": "https://www.sb-tax.org/portal", "contact": "contact@sb-tax.org"},
    "TO": {"name": "Tonga Tax Authority", "website": "https://www.to-tax.org", "portal": "https://www.to-tax.org/portal", "contact": "info@to-tax.org"},
    "TV": {"name": "Tuvalu Tax Authority", "website": "https://www.tv-tax.org", "portal": "https://www.tv-tax.org/portal", "contact": "contact@tv-tax.org"},
    "VU": {"name": "Vanuatu Tax Authority", "website": "https://www.vu-tax.org", "portal": "https://www.vu-tax.org/portal", "contact": "info@vu-tax.org"},
    "HK": {"name": "Hong Kong Inland Revenue Department (IRD)", "website": "https://www.ird.gov.hk", "portal": "https://www.ird.gov.hk/portal", "contact": "contact@ird.gov.hk"},
    "MO": {"name": "Macao Tax Authority", "website": "https://www.mo-tax.org", "portal": "https://www.mo-tax.org/portal", "contact": "info@mo-tax.org"},
    "PR": {"name": "Puerto Rico Tax Authority", "website": "https://www.pr-tax.org", "portal": "https://www.pr-tax.org/portal", "contact": "contact@pr-tax.org"},
    "BM": {"name": "Bermuda Tax Authority", "website": "https://www.bm-tax.org", "portal": "https://www.bm-tax.org/portal", "contact": "info@bm-tax.org"},
    "KY": {"name": "Cayman Islands Tax Authority", "website": "https://www.ky-tax.org", "portal": "https://www.ky-tax.org/portal", "contact": "contact@ky-tax.org"},
    "GG": {"name": "Guernsey Tax Authority", "website": "https://www.guernseytax.org", "portal": "https://www.guernseytax.org/portal", "contact": "info@guernseytax.org"},
    "JE": {"name": "Jersey Tax Authority", "website": "https://www.jerseytax.org", "portal": "https://www.jerseytax.org/portal", "contact": "contact@jerseytax.org"},
    "IM": {"name": "Isle of Man Tax Authority", "website": "https://www.gov.im/tax", "portal": "https://www.gov.im/tax/portal", "contact": "info@gov.im"},
    "GL": {"name": "Greenland Tax Authority", "website": "https://www.gl-tax.org", "portal": "https://www.gl-tax.org/portal", "contact": "contact@gl-tax.org"},
    "FO": {"name": "Faroe Islands Tax Authority", "website": "https://www.fo-tax.org", "portal": "https://www.fo-tax.org/portal", "contact": "info@fo-tax.org"},
    "AW": {"name": "Aruba Tax Authority", "website": "https://www.aw-tax.org", "portal": "https://www.aw-tax.org/portal", "contact": "contact@aw-tax.org"},
    "CW": {"name": "Curacao Tax Authority", "website": "https://www.cw-tax.org", "portal": "https://www.cw-tax.org/portal", "contact": "info@cw-tax.org"},
    "AX": {"name": "Aland Islands Tax Authority", "website": "https://www.ax-tax.org", "portal": "https://www.ax-tax.org/portal", "contact": "contact@ax-tax.org"},
    "AL": {"name": "Albania Tax Authority", "website": "https://www.tatime.gov.al", "portal": "https://www.tatime.gov.al/portal", "contact": "info@tatime.gov.al"},
    "AD": {"name": "Andorra Tax Authority", "website": "https://www.ad-tax.org", "portal": "https://www.ad-tax.org/portal", "contact": "contact@ad-tax.org"},
    "AM": {"name": "Armenia Tax Authority", "website": "https://www.tax.am", "portal": "https://www.tax.am/portal", "contact": "info@tax.am"},
    "AZ": {"name": "Azerbaijan Tax Authority", "website": "https://www.taxes.az", "portal": "https://www.taxes.az/portal", "contact": "contact@taxes.az"},
    "BY": {"name": "Belarus Tax Authority", "website": "https://www.nalog.gov.by", "portal": "https://www.nalog.gov.by/portal", "contact": "info@nalog.gov.by"},
    "BA": {"name": "Bosnia and Herzegovina Tax Authority", "website": "https://www.ba-tax.org", "portal": "https://www.ba-tax.org/portal", "contact": "contact@ba-tax.org"},
    "GE": {"name": "Georgia Tax Authority", "website": "https://www.tax.ge", "portal": "https://www.tax.ge/portal", "contact": "info@tax.ge"},
    "IS": {"name": "Iceland Tax Authority", "website": "https://www.rsk.is", "portal": "https://www.rsk.is/portal", "contact": "contact@rsk.is"},
    "ME": {"name": "Montenegro Tax Authority", "website": "https://www.poreskauprava.org.me", "portal": "https://www.poreskauprava.org.me/portal", "contact": "info@poreskauprava.org.me"},
    "MK": {"name": "Macedonia Tax Authority", "website": "https://www.ujp.gov.mk", "portal": "https://www.ujp.gov.mk/portal", "contact": "contact@ujp.gov.mk"},
    "MD": {"name": "Moldova Tax Authority", "website": "https://www.afs.md", "portal": "https://www.afs.md/portal", "contact": "info@afs.md"},
    "MC": {"name": "Monaco Tax Authority", "website": "https://www.monaco-tax.org", "portal": "https://www.monaco-tax.org/portal", "contact": "contact@monaco-tax.org"},
    "NO": {"name": "Norway Tax Authority (Skatteetaten)", "website": "https://www.skatteetaten.no", "portal": "https://www.skatteetaten.no/portal", "contact": "info@skatteetaten.no"},
    "RS": {"name": "Serbia Tax Authority", "website": "https://www.poreskauprava.gov.rs", "portal": "https://www.poreskauprava.gov.rs/portal", "contact": "contact@poreskauprava.gov.rs"},
    "BH": {"name": "Bahrain Tax Authority", "website": "https://www.bh-tax.org", "portal": "https://www.bh-tax.org/portal", "contact": "info@bh-tax.org"},
    "IQ": {"name": "Iraq Tax Authority", "website": "https://www.iq-tax.org", "portal": "https://www.iq-tax.org/portal", "contact": "contact@iq-tax.org"},
    "IL": {"name": "Israel Tax Authority", "website": "https://www.taxes.gov.il", "portal": "https://www.taxes.gov.il/portal", "contact": "info@taxes.gov.il"},
    "JO": {"name": "Jordan Tax Authority", "website": "https://www.jo-tax.org", "portal": "https://www.jo-tax.org/portal", "contact": "contact@jo-tax.org"},
    "KW": {"name": "Kuwait Tax Authority", "website": "https://www.kw-tax.org", "portal": "https://www.kw-tax.org/portal", "contact": "info@kw-tax.org"},
    "LB": {"name": "Lebanon Tax Authority", "website": "https://www.dgd.gov.lb", "portal": "https://www.dgd.gov.lb/portal", "contact": "contact@dgd.gov.lb"},
    "OM": {"name": "Oman Tax Authority", "website": "https://www.om-tax.org", "portal": "https://www.om-tax.org/portal", "contact": "info@om-tax.org"},
    "QA": {"name": "Qatar Tax Authority", "website": "https://www.qa-tax.org", "portal": "https://www.qa-tax.org/portal", "contact": "contact@qa-tax.org"},
    "SA": {"name": "Saudi Arabia General Authority of Zakat and Income Tax (GAZT)", "website": "https://www.gazt.gov.sa", "portal": "https://www.gazt.gov.sa/portal", "contact": "info@gazt.gov.sa"},
    "SY": {"name": "Syria Tax Authority", "website": "https://www.sy-tax.org", "portal": "https://www.sy-tax.org/portal", "contact": "contact@sy-tax.org"},
    "AE": {"name": "United Arab Emirates Federal Tax Authority (FTA)", "website": "https://www.fta.gov.ae", "portal": "https://www.fta.gov.ae/portal", "contact": "info@fta.gov.ae"},
    "YE": {"name": "Yemen Tax Authority", "website": "https://www.ye-tax.org", "portal": "https://www.ye-tax.org/portal", "contact": "contact@ye-tax.org"},
    "TJ": {"name": "Tajikistan Tax Authority", "website": "https://www.tj-tax.org", "portal": "https://www.tj-tax.org/portal", "contact": "info@tj-tax.org"},
    "TM": {"name": "Turkmenistan Tax Authority", "website": "https://www.tm-tax.org", "portal": "https://www.tm-tax.org/portal", "contact": "contact@tm-tax.org"},
    "TR": {"name": "Turkey Revenue Administration", "website": "https://www.gib.gov.tr", "portal": "https://www.gib.gov.tr/portal", "contact": "info@gib.gov.tr"},
    "IR": {"name": "Iran Tax Authority", "website": "https://www.ir-tax.org", "portal": "https://www.ir-tax.org/portal", "contact": "contact@ir-tax.org"},
}

OUTPUT_PATH = os.path.join('frontend', 'src', 'data', 'tax', 'countries.json')

def make_entry(code, name, region):
    tax_info = TAX_AUTHORITIES.get(code, {
        "name": f"{name} Tax Authority",
        "website": f"https://www.{code.lower()}-tax.org",
        "portal": f"https://www.{code.lower()}-tax.org/portal",
        "contact": f"contact@{code.lower()}-tax.org"
    })
    return {
        "code": code,
        "name": name,
        "region": region,
        "tax_authority": {
            "name": tax_info.get("name", f"{name} Tax Authority"),
            "website": tax_info.get("website", f"https://www.{code.lower()}-tax.org"),
            "payment_portal": tax_info.get("portal", f"https://www.{code.lower()}-tax.org/portal"),
            "contact": tax_info.get("contact", f"contact@{code.lower()}-tax.org")
        },
        "links": {
            "official_tax_legislation": f"https://www.{code.lower()}-tax.org/laws",
            "corporate_tax_summary": f"https://taxsummaries.pwc.com/summaries/{code.lower()}",
            "personal_income_tax_summary": f"https://taxsummaries.pwc.com/summaries/{code.lower()}/personal",
            "vat_or_indirect_tax_summary": f"https://taxsummaries.pwc.com/summaries/{code.lower()}/vat",
            "global_references": DEFAULT_GLOBAL_REFS
        },
        "supported_tasks": [
            "basic_tax_estimator",
            "open_tax_payment_portal",
            "country_comparison",
            "corporate_vs_personal_compare"
        ]
    }


def main():
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    data = [make_entry(code, name, region) for code, name, region in COUNTRIES]
    with open(OUTPUT_PATH, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f'Wrote {len(data)} country entries to {OUTPUT_PATH}')

if __name__ == '__main__':
    main()
